version: '3'

services:

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  app:
    image: adrianpereira/random-user-insert-node-app-mysql:prod
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh index.js
    networks:
      - node-network
    depends_on:
      - db

  nginx:
    image: adrianpereira/random-user-insert-nginx-node:prod
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:8080"
    depends_on:
      - app

networks:
  node-network:
    driver: bridge